[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "Guitar"
  url = "http://ngthanhtin.github.io/blog/post/guitar/guitar/"
  weight = -109

[[main]]
  name = "List 100"
  url = "http://ngthanhtin.github.io/blog/post/personal/list100/"
  weight = -108

[[main]]
  name = "CV of Failures"
  url = "https://ngthanhtin.github.io/aboutme/failure.html"
  weight = -107

[[main]]
  name = "Books"
  identifier = "Books"
  weight = -106
[[main]]
  parent = "Books"
  name = "AI"
  url = "http://ngthanhtin.github.io/blog/post/books/ai/"
[[main]]
  parent = "Books"
  name = "Misc"
  url = "http://ngthanhtin.github.io/blog/post/books/misc/"

# Submenus are done this way: parent -> identifier
[[main]]
  name = "Resources"
  identifier = "Resources"
  weight = -105
[[main]]
  parent = "Resources"
  name = "Notion"
  url = "https://www.notion.so/Reading-List-6ea548b6dd32447bb4dc605cb9a4c446"
[[main]]
  parent = "Resources"
  name = "Calendar"
  url = "https://calendar.notion.so/"

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/ngthanhtin"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/TnNguyn21237605"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/kevin-nguyen-836806221/"
[[social]]
  name = "instagram"
  weight = 4
  url = "https://www.instagram.com/fuhodev/"
[[social]]
  name = "rss"
  weight = 5
  url = "https://ngthanhtin.github.io/"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "discord"
# url = "https://discord.gg/#"